version: '3.4'
services:
  kaiml-eda:
    build: 
      context: .
      dockerfile: ./docker/pip-based/Dockerfile
    image: kaiml/lease-eda:latest
    ports:
    - "8888:8888"
    volumes:
    - .:/app
