version: '3.4'
services:
  kaiml-eda:
    build: .
    image: kaiml/lease-eda:latest
    ports:
    - "8888:8888"
    volumes:
    - ./src:/app
    command: pipenv run jupyter notebook --ip 0.0.0.0 --no-browser --allow-root