version: '3.4'
services:
  kaiml-eda:
    build: .
    image: kaiml/lease-eda
    ports:
    - "8888:8888"
    volumes:
    -  ./input:/app/input
    -  ./notebook:/app/notebook
    command: pipenv run jupyter notebook --ip 0.0.0.0 --no-browser --allow-root