name: Docker Build Image
on:
  push:
    paths:
      - "Dockerfile"
      - "Pipfile.lock"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build . -t lease-eda:test
