name: Publish Image to DockerHub
on:
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
      - "Pipfile.lock"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Image to DockerHub
        run: |
          cd $GITHUB_WORKSPACE
          echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
          BASE_NAME="kaiml/lease"
          IMAGE_NAME="$BASE_NAME:latest"
          docker pull $IMAGE_NAME || true
          docker build --cache-from $BASE_NAME -t $IMAGE_NAME -t $BASE_NAME -f Dockerfile .
          docker push $IMAGE_NAME
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }
